---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
- job_name: snippetbox
  scheme: https
  static_configs:
    - targets: ["localhost:4001"]
  tls_config:
      insecure_skip_verify: true